export const dsDivisions = {
  Badulla: [
    'Badulla', 'Bandarawela', 'Ella', 'Haldummulla', 'Hali-Ela',
    'Haputale', 'Kandaketiya', 'Lunugala', 'Mahiyanganaya',
    'Meegahakivula', 'Passara', 'Rideemaliyadda', 'Soranathota',
    'Uva Paranagama', 'Welimada'
  ],
  Monaragala: [
    'Badalkumbura', 'Bibile', 'Buttala', 'Kataragama', 'Madulla',
    'Medagama', 'Moneragala', 'Sevanagala', 'Siyambalanduwa',
    'Thanamalwila', 'Wellawaya'
  ]
};

export const gsDivisionsData = {
  Badulla: ['Andeniya','Badulla Central','Badulla East','Badulla North','Badulla South','Badulla West','Badulupitiya','Damanwara','Glen Alpin','Hegoda','Hindagoda','Hingurugamuwa','Hinnarangolla','Ilukthenna','Kailagoda','Kanupelella','Katupelella','Kendagolla','Malangamuwa','Medapathana','Pitawelagama','Rambukpotha','Sirimalgoda','Thelbedda Estate','Udawela','Vineethagama','Viyadiguna','Welibissa','Wewessa'],
  Bandarawela: ['Ambadandegama','Ambegoda','Bambaragama','Bandarawela East','Bandarawela West','Beddearawa','Beddekumbura','Bindunuwewa','Creig Watta','Darahitawanagoda','Diganathenna','Dulgolla','Egodagama','Etthalapitiya','Gediyaroda','Icelab Watta','Inikambedda','Karagahawela','Kebillawela North','Kebillawela South','Kinigama','Kirioruwa','Konthahela','Liyangahawela','Liyangahawela Watta','Mahaulpatha','Makulella','Mathetilla','Nayabedda Estate','Obadella','Thanthiriya','Udaperuwa','Watagamuwa','Weheragalathenna','Wewathenna'],
  Ella: ['Ballaketuwa','Beddewela','Demodara','Dodamgolla','Dowa','Ella','Galtanhena','Gawarawela','Govussa','Halpe','Heeloya','Hettipola','Idamegama','Ilukpelessa','Karandagolla','Kirinda','Kithalella','Madhuragama','Medawela West','Millagama','Namunukula','Naulla','Nawela East','Nawela West','Newberg','Palleperuwa','Piyarapandowa','Pupula','Pupula West','Rawanaella','Udu Kumbalwela','Yahalewela'],
  Haldummulla: ['Akkaraseeya','Amilagama','Ampitiyathenna','Bambarapokuna','Beragala','Divulgasmulla','Gampaha','Haldummulla','Harankahawa','Kalupahana','Kelipanawela','Kirawanagama','Kithulgahaarawa','Kolongasthenna','Kosgama','Koslanda','Kotabakma','Lemasthota','Mahakanda','Mahalanda','Manthenna','Marangahawela','Medawela','Moraketiya','Nikapotha East','Nikapotha West','Poonagalla','Ranasinghegama','Ranwanguhawa','Seelathenna','Soragune','Uvathenna','Viharagala','Walhaputhenna','Watagamuwa','Weeliya','Weerakongama','Welanwita','Welibissa'],
  'Hali-Ela': ['Anthuduwawela','Beddegama','Bogahamaditta','Bogoda','Bulathwatta','Deegalla','Dehiwinna','Dematawelhinna','Dikwella','Etampitiya','Gawela','Godegama','Haliela','Hapuwalakumbura','Hethekma','Hinnaranagolla','Imbulgoda','Jangulla','Kandana','Katugaha','Ketawala','Kirinda','Kokatiyamaluwa','Kottagoda','Kudumahuwela','Kurukude','Landewela','Mahathenna','Mahawattagama','Maligathenna','Malitta','Medagama','Medapitigama','Morethota','Mugunumatha East','Mugunumatha West','Neludanda','Neluwa','Niliathugoda','Pahamunuthota','Pallegama','Panakanniya','Pattipola','Perahettiya','Samagipura','Springvalley','Springvalley Estate','Udagama','Udakohovila','Uduwara','Unagolla','Uva Mahawela','Warakadanda','Wegama','Welikemulla','Wepassawela','Wewelhinna'],
  Haputale: ['Aluthwela','Bingethenna','Dambethenna','Diyathalawa','Dodamwatta','Ellagama','Eranawela','Galkanda','Glananor Watta','Haputala Town','Haputhalegama','Hela Kadurugamuwa','Horadorowwa','Jayaminipura','Kahagolla','Kahathewela','Kolathenna','Magiripura','Pahala Kadurugamuwa','Panketiya','Pitarathamale','Ranjallawa','Thotalagala','Umankandura','Viharakele','Welanhinna'],
  Kandaketiya: ['Badulluoya West','Baduluoya East','Beramada','Bogahakumbura','Bokanoruwa','Bopitiya','Dikkumbura','Galauda','Godunna','Hapathgamuwa','Hevandana','Kandakepu Ulpotha','Kandaketiya','Kirivehera','Kivulegedara','Mahakele','Mahathenna','Maliyadda','Mudagamuwa','Narangala','Pallewela','Thalakumbura','Thetilla','Wasanagama','Welaoya','Wewathenna'],
  Lunugala: ['Alakolagala','Arawakumbura','Attanagolla','Batawatta','Ekiriya','Gallulla','Galwelagama','Hopton','Janathapura','Janathapura North','Janathapura South','Kottalbedda','Lunugala Town','Madulsima','Maduwatta','Mahadowa','Metigahathenna','Millabedda','Pallekiruwa','Peessagama','Rendapola','Sooriyagoda','Sumudugama','Udakiruwa','Udapanguwa','Weragoda','Wewabedda','Yapamma'],
  Mahiyanganaya: ['Aluttarama','Aluyatawala','Bathalayaya','Belaganwewa','Beligalla','Dambagolla','Dambana','Dambarawa','Dehigolla','Divulapelessa','Elewela','Galporuyaya','Ginnoruwa','Girandurukotte','Haddattawa','Hebarawa','Hobariyawa','Kukulapola','Mahiyangana Town','Mapakadawewa','Medayaya','Meegahahena','Millattawa','Pahala Rathkinda','Pangaragammana','Poojanagaraya','Rotalawela','Senanigama','Sorabora','Thalangamuwa','Theldeniyaya','Ulhitiya','Wewatta','Wewgampaha','Wiranegama'],
  Meegahakivula: ['Aggalaulpotha','Akurukaduwa','Balagolla','Ellanda','Hunuketapitiya','Kalugahakandura','Karametiya','Karandagahamada','Ketawatta','Kohana','Komarika','Meegahakivula','Morahela','Pitamaruwa','Polgahaarawa','Polwatta','Roberiya','Thaldena','Watagommana','Wewathenna'],
  Passara: ['Ambathenna','Ambathenna West','Bibilegama East','Bibilegama West','Dambakote','Dambewela','Demodara','Gerandiella','Gonagala East','Gonagala West','Kahataruppa','Kanahela','Kanawerella','Kanawerella East','Kanawerella West','Kudugala Pathana','Madugasthalawa North','Madugasthalawa South','Maligathenna','Maussagolla East','Maussagolla West','Medawelagama','Meedumpitiya','Meeriyabedda','Nikebedda','Palagolla','Palawatta','Pallegama','Paramahankada','Passara Town East','Passara Town North','Passara Town South','Pelgahathenna','Puhulwatta','Supuroda','Thalagahagedara','Thennuge','Tholabolawatta','Udagama','Welgolla','Wewekele'],
  Rideemaliyadda: ['Abhayapura','Aluketiyawa','Andaulapatha','Aralupitiya','Arawa','Arawatta','Bubula','Deekirigolla','Dehigama','Dikkendayaya','Dikyaya','Diyakombala','Ekiriyankumbura','Gamakumbura North','Gamakumbura South','Ikiriyagoda','Kandegama','Kandubedda','Keselpotha North','Keselpotha South','Kooralewela','Kotathalawa','Kudalunuka','Kuruvithenna','Mahagama','Mahalunuka','Morana','Nagadeepa','Orubendiwewa','Pahalaoyagama','Pethiyagoda','Pinnagolla','Rideemaliyadda North','Rideemaliyadda South','Ritigahaarawa','Sangabopura','Senewigama','Serana','Uraniya','Uva Gemunupura','Uva Thissapura','Welampele'],
  Soranathota: ['Ambagasdowa','Angoda','Boliyadda','Budugekanda','Dikpitiya','Egodawela','Idamegama','Idamepanguwa','Kandegedara Town','Ketakellagama','Kirioruwa','Kithulwattagama','Kohowila','Kosgolla','Kuttiyagolla','Ledger Watta','Moragolla','Pallekanda','Pathanegedara','Pussellakanda','Pussellawa','Rideepana','Soranathota','Wattekele','Yatilellagama'],
  'Uva Paranagama': ['Alagolla','Ambagasdowa','Balagala','Bambarapana','Beraliyapola','Busdulla','Dangamuwa','Daragala','Dimbulana','Downside','Ellanda','Ethkandawaka','Galahagama','Gampaha','Hangiliella','Hangunnawa','Hathkinda','Idamegama','Ilukwela','Karagahaulpatha','Kendagolla','Kerklis','Ketagoda','Kindigoda','Kirawanagama','Kodakumbura','Kohilegama','Korandekumbura','Kotawara Udagama','Kotawera Pahalagama','Kumarapattiya','Kurundugolla','Lunuwatta','Malapolagama','Malwatte Gama','Maspanna','Medagoda Gama','Medawela','Medipokuna','Metiwalalanda','Mudanawa','Pallewela','Panagoda','Pannalagama','Pannalawela','Paranagama','Perawella','Pitiyakumbura','Rahupola','Ranhawadi Gama','Rathamba','Ritikumbura','Sapugolla','Thawalampola','Thelhawadigama','Thuppitiya','Udaperuwa','Uduhawara','Ulugala','Uma Ela','Unapana','Vondmar','Welamedagama','Weliulla','Wethalawa','Wewegama','Yahala Arawa','Yalagamuwa'],
  Welimada: ['Alakolagala','Alawathugoda','Alugolla','Ambagahakumbura','Ambewela','Bibiligamuwa','Bogahakumbura','Boragas','Boralanda','Dambawenna','Dayabarawatta','Dikkapitiya','Dimuthugama','Divithotawela','Divurumgama','Erabadda','Galedanda','Gavarammana','Girambe','Guruthalawa','Helayalkumbura','Hewanakumbura','Himbiliyagolla','Hingurugamuwa','Hinnarangolla','Hulankapolla','Idamegama','Kabillegama','Kalubululanda','Kandepuhulpola','Karagasthenna','Keppetipola','Ketakella','Koskanuwegama','Kotakithula','Landegama','Mahathenna','Maligathenna','Malpotha','Mawithikumbura','Medagedaragama','Merahawatta','Nawela','Nedungamuwa','Ohiya','Ohiya Watta','Pahala Yalkumbura','Palugama Ella','Palugama Town','Pitapola','Puhulpola','Puranwela','Rahangala','Rathkarawwa','Silmiyapura','Thennakonwela','Udakandagolla','Udupeella','Vidurupola','Wangiyakumbura','Welikadagama','Welimada Town','Welimadawatta','Yalpathwela'],
  Badalkumbura: ['Alupotha','Ankada','Athala','Badalkumbura','Bogahapelessa','Dambagahawela','Dewathura','Ella','Ethpattiya','Ettalamulla','Gadavila','Hingurukaduwa','Kalagahakivula','Karandagama','Karavila','Katugahagalge','Keliwessa','Kotamuduna','Lunugala Colony','Madamagama','Madugahapattiya','Madugasmulla','Madukotan Arawa','Mailagasthenna','Maiyokka Watta','Maligathenna','Meegahayaya','Miyanakandura','Moratuwagama','Muthukeliyawa','Naranwatta','Pallegama','Punsisigama','Pussellawa','Ranugalla','Thalawagama','Therappahuwa','Waradola','Wasipaha','Wekumbura','Yakurawa'],
  Bibile: ['Ambagolla','Ambelanda','Badulla gammana','Bibila','Bokagonna','Bulupitiya','Dehiattawela','Dodamgolla','Egoda kotagama','Ethanawatta','Hamapola','Hewelwela','Kanawegalla','Kanulwela','Karagahawela East','Karagahawela West','Karandugala','Kawdella','Kehelattawela','Kokunnawa','Kotagama','Kuruwamba','Lindakumbura','Mallahawa','Medipitiya','Moodiyala','Morattamulla','Nagala','Nilgala','Pitakumbura','Radaliyadda','Rathupaskatiya','Thanayamgama','Thotillaketiya','Udamallahawa','Urawula','Ussagala','Wegama','Wegama South','Yalkumbura'],
  Buttala: ['Buruthagolla','Dikyaya','Galtemmandiya','Gaminipura','Gonagan Ara','Horabokka','Konketiya','Kukurampola','Kumaragama','Kumarapura','Mahagodayaya','Mahasenpura','Maligavila','Medagama','Minipuragama','Okkampitiya','Pahalagama','Pelwatta','Pettagamwela','Puhulkotuwa','Rahathangama','Uda Arawa','Udagama','Ulugala','Unawatuna','Veheragala','Waguruwela','Yatiyallathota','Yudaganawa'],
  Kataragama: ['Detagamuwa','Kandasurindugama','Karavile','Kataragama','Sella Kataragama'],
  Madulla: ['Alpitiya','Alugalge','Aratugaswela','Baduluwela','Bandarawadiya','Dambagalla','Deliwa','Ellekona','Galbokka','Galgamuwa','Gangoda Arawa','Gangodagama','Gonathalawa','Iginiyagala','Ihawa','Iluklanda','Kahagolla','Kolladeniya','Kottagala','Magandana','Magandaoya Colony','Makulla','Mariarawa','Mullegama','Namaloya Colony','Neelawa Bedda','Nelliyadda','Obbegoda','Pagura','Panguwa','Polgahagama','Ritigahawatta','Ruwalwela','Thalkotayaya','Thampalawela','Therela','Udumulla','Watawanagama'],
  Medagama: ['Alana','Amunekandura','Bakinigahawela','Bendiyawa','Bibilamulla','Dahagoniya','Dahamgama','Diviyapola','Elhena','Ellekoona','Godigamuwa','Ilukkumbura','Iwela','Kalugahawadiya','Keenagoda','Kendawinna','Kinnaraboowa','Kohukumbura','Koongolla','Kotabowa','Medagama','Mellagama','Monarawana','Nannapurawa','Nugamura','Pitadeniya','Polgahapitiya','Pothubandana','Pubbara','Raththanadeniaya','Senapathiya','Senpathigama','Thambana','Thimbiriya','Yakunnawa'],
  Moneragala: ['Aliyawatta','Batugammana','Bohitiya','Debeddekivla','Guruhela','Hidikiwla','Horombuwa','Hulandawa','Hulandawa Left','Hulandawa South','Kahambana','Kawdawa','Kolonvinna','Kumbukkana','Maduruketiya','Magandanamulla','Marawa','Monaragala','Muppane','Nakkala','Rathnapitiya','Tenwatta','Thenagallanda','Veheragala','Viharamulla','Weliyaya'],
  Sevanagala: ['Bahirawa','Habaraluwewa','Habarattawela','Habarugala','Indikolapelessa','Katupilagama','Kiriibbanwewa','Mahagama','Muthuminigama','Nugegalayaya','Punchiwewa','Samagipura','Sevanagala','Weliara'],
  Siyambalanduwa: ['Ambagahapitiya','Barawaya','Beraliyapola','Buddama','Dombagahawela','Ethimale','Ethimale Colony','Galamuna','Gemunupura','Govindupura','Guruhela','Helamulla','Indigasella','Kalugollayaya','Karambagoda','Kimbulawela','Kivuleyaya','Kodayana','Kooragammana','Kotagoda','Kotiyagala','Kotiyagoda','Liyangolla','Madugama','Maha Kalugolla','Manabarana','Meeyagala','Minipura','Muthukandiya','Nape','Newgala','Nugagaha Kivula','Pahatha Arawa','Pallegama','Pallewela','Parakumpura','Ruhunu Danawwa','Samanala Bedda','Siripura','Siyambalanduwa','Sri Wijithapura','Thissapura','Vilaoya','Waragama','Wattegama','Weragoda','Wijayapura','Yakkandurawa'],
  Thanamalwila: ['Aluthwewa','Bodagama','Hambegamuwa','Hambegamuwa Colony','Kahakurullan Pelessa','Kandiyapitawewa','Kivul Ara','Kotaweheramankada','Mahawewa','Nikawewa','Sienukkuwa','Sittarama','Suriya Ara','Usgala'],
  Wellawaya: ['Anapallama','Andawelayaya','Balaharuwa','Buduruwagala','Debara Ara','Dimbulamure','Ethiliwewa','Gallbokka','Handapanagala','Kithulkote','Kotikanbokka','Kurugama','Maha Aragama','Neluwagala','Nugayaya','Pubuduwewa','Randenigodayaya','Randeniya','Siripuragama','Siyambalagunaya','Sudupanawela','Thelulla','Thelulla Colony','Uva Kudaoya','Veherayaya','Veherayaya Colony','Warunagama','Wellawaya','Yalabowa']
};
